### ISSUE TITLE
Soundness issue on QF_FP formula

### ISSUE THREAD

**Issue by rainoftime** [bitwuzla/bitwuzla.github.io#1]
Hi, when solving the following formula, bitwuzla (the fixed version of the smt-comp20 binary (https://www.starexec.org/starexec/secure/details/solver.jsp?id=29091) yields `sat`.
However, the formula should be `unsat`.
Is this because some predicates are not modeled yet? 
~~~~
(set-logic QF_FP)
(declare-const fpv0 Float32)
(assert (fp.isNegative (fp.abs fpv0)))
(check-sat)
~~~~

**Comment by mpreiner** [comment]
Thanks for the report, we'll look into it. This is the bitwuzla website repository and should not be used for solver issues.
